version: '3'
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "6033:3306"
    networks:
      - mysql-net
    volumes:
      - ./data/db:/var/lib/mysql    
networks:
  mysql-net:
    external: true
